
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox7;

	private global::Gtk.HBox hbox27;

	private global::Gtk.Label label11;

	private global::Gtk.Entry entry11;

	private global::Gtk.VBox vbox11;

	private global::Gtk.HBox hbox29;

	private global::Gtk.Label label13;

	private global::Gtk.Entry entry13;

	private global::Gtk.HBox hbox31;

	private global::Gtk.Label label15;

	private global::Gtk.Entry entry15;

	private global::Gtk.HBox hbox33;

	private global::Gtk.HBox hbox35;

	private global::Gtk.Button button5;

	private global::Gtk.Button button7;

	private global::Gtk.Button button9;

	private global::Gtk.HBox hbox37;

	private global::Gtk.Button button11;

	private global::Gtk.Button button13;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox27 = new global::Gtk.HBox();
		this.hbox27.Name = "hbox27";
		this.hbox27.Spacing = 6;
		// Container child hbox27.Gtk.Box+BoxChild
		this.label11 = new global::Gtk.Label();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Number 1");
		this.hbox27.Add(this.label11);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox27[this.label11]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox27.Gtk.Box+BoxChild
		this.entry11 = new global::Gtk.Entry();
		this.entry11.CanFocus = true;
		this.entry11.Name = "entry11";
		this.entry11.IsEditable = true;
		this.hbox27.Add(this.entry11);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox27[this.entry11]));
		w2.Position = 1;
		this.vbox7.Add(this.hbox27);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox27]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.vbox11 = new global::Gtk.VBox();
		this.vbox11.Name = "vbox11";
		this.vbox11.Spacing = 6;
		// Container child vbox11.Gtk.Box+BoxChild
		this.hbox29 = new global::Gtk.HBox();
		this.hbox29.Name = "hbox29";
		this.hbox29.Spacing = 6;
		// Container child hbox29.Gtk.Box+BoxChild
		this.label13 = new global::Gtk.Label();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Number 2");
		this.hbox29.Add(this.label13);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.label13]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox29.Gtk.Box+BoxChild
		this.entry13 = new global::Gtk.Entry();
		this.entry13.CanFocus = true;
		this.entry13.Name = "entry13";
		this.entry13.IsEditable = true;
		this.hbox29.Add(this.entry13);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox29[this.entry13]));
		w5.Position = 1;
		this.vbox11.Add(this.hbox29);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hbox29]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.hbox31 = new global::Gtk.HBox();
		this.hbox31.Name = "hbox31";
		this.hbox31.Spacing = 6;
		// Container child hbox31.Gtk.Box+BoxChild
		this.label15 = new global::Gtk.Label();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Result");
		this.hbox31.Add(this.label15);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.label15]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox31.Gtk.Box+BoxChild
		this.entry15 = new global::Gtk.Entry();
		this.entry15.CanFocus = true;
		this.entry15.Name = "entry15";
		this.entry15.IsEditable = true;
		this.hbox31.Add(this.entry15);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox31[this.entry15]));
		w8.Position = 1;
		this.vbox11.Add(this.hbox31);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hbox31]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.hbox33 = new global::Gtk.HBox();
		this.hbox33.Name = "hbox33";
		this.hbox33.Spacing = 6;
		// Container child hbox33.Gtk.Box+BoxChild
		this.hbox35 = new global::Gtk.HBox();
		this.hbox35.Name = "hbox35";
		this.hbox35.Spacing = 6;
		// Container child hbox35.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("Add");
		this.hbox35.Add(this.button5);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox35[this.button5]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox35.Gtk.Box+BoxChild
		this.button7 = new global::Gtk.Button();
		this.button7.CanFocus = true;
		this.button7.Name = "button7";
		this.button7.UseUnderline = true;
		this.button7.Label = global::Mono.Unix.Catalog.GetString("Subtract");
		this.hbox35.Add(this.button7);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox35[this.button7]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox35.Gtk.Box+BoxChild
		this.button9 = new global::Gtk.Button();
		this.button9.CanFocus = true;
		this.button9.Name = "button9";
		this.button9.UseUnderline = true;
		this.button9.Label = global::Mono.Unix.Catalog.GetString("Multiply");
		this.hbox35.Add(this.button9);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox35[this.button9]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.hbox33.Add(this.hbox35);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox33[this.hbox35]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox33.Gtk.Box+BoxChild
		this.hbox37 = new global::Gtk.HBox();
		this.hbox37.Name = "hbox37";
		this.hbox37.Spacing = 6;
		// Container child hbox37.Gtk.Box+BoxChild
		this.button11 = new global::Gtk.Button();
		this.button11.CanFocus = true;
		this.button11.Name = "button11";
		this.button11.UseUnderline = true;
		this.button11.Label = global::Mono.Unix.Catalog.GetString("Divide");
		this.hbox37.Add(this.button11);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox37[this.button11]));
		w14.Position = 0;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox37.Gtk.Box+BoxChild
		this.button13 = new global::Gtk.Button();
		this.button13.CanFocus = true;
		this.button13.Name = "button13";
		this.button13.UseUnderline = true;
		this.button13.Label = global::Mono.Unix.Catalog.GetString("Reset");
		this.hbox37.Add(this.button13);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox37[this.button13]));
		w15.Position = 1;
		w15.Expand = false;
		w15.Fill = false;
		this.hbox33.Add(this.hbox37);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox33[this.hbox37]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		this.vbox11.Add(this.hbox33);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hbox33]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		this.vbox7.Add(this.vbox11);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.vbox11]));
		w18.Position = 1;
		w18.Expand = false;
		w18.Fill = false;
		this.Add(this.vbox7);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button5.Clicked += new global::System.EventHandler(this.OnButton5Clicked);
		this.button7.Clicked += new global::System.EventHandler(this.OnButton7Clicked);
		this.button9.Clicked += new global::System.EventHandler(this.OnButton9Clicked);
		this.button11.Clicked += new global::System.EventHandler(this.OnButton11Clicked);
		this.button13.Clicked += new global::System.EventHandler(this.OnButton13Clicked);
	}
}
